export const LIST_USERS = 'LIST_USERS'
export const CREATE_USER = 'CREATE_USER'
export const DISPLAY_USER = 'DISPLAY_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'